# Generated by Django 5.1 on 2024-08-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calibration_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
