# Generated by Django 5.1 on 2024-09-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_calibration_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='calibration_data',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
