# Generated by Django 5.1 on 2024-10-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tts_volume',
            field=models.FloatField(default=1.0),
        ),
    ]
