# Generated by Django 5.1 on 2024-10-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_tts_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calibration_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
